<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Za konto_firstName</name>
   <tag></tag>
   <elementGuidId>fa101136-bf08-43d0-99b4-7559d5506f62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;firstName&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='firstName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>given-name</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Imię (wymagane)</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>firstName</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>sc-1k5v2vw-1 gPbfDu sc-3ncbnj-3 imstYS</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;sc-3vw8wn-2 jZrGnj sc-14ybyi4-0 hsHTNN&quot;]/div[@class=&quot;sc-3vw8wn-4 jFMeVo sc-bwzfXH kagohx&quot;]/div[@class=&quot;sc-bwzfXH sc-htpNat gSgMmi&quot;]/div[@class=&quot;raujvo-3 dUMVJW sc-bwzfXH gHjklt&quot;]/div[@class=&quot;raujvo-2 WvowS&quot;]/form[@class=&quot;qtqqzt-1 fpfkvo&quot;]/div[@class=&quot;qtqqzt-0 iChQhx&quot;]/div[@class=&quot;qtqqzt-2 fOhgrH sc-1k5v2vw-0 ehAwGQ&quot;]/label[@class=&quot;sc-1k5v2vw-1 gPbfDu sc-3ncbnj-0 dmbMDt&quot;]/input[@class=&quot;sc-1k5v2vw-1 gPbfDu sc-3ncbnj-3 imstYS&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='firstName']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/div/div/div/form/div/div/label/input</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
   </webElementXpaths>
</WebElementEntity>
